### ISSUE TITLE
Question: Is XML human-generated?

### ISSUE THREAD

**Issue by jclab-joseph** [open-amt-cloud-toolkit/wsman-messages#663]
I have a question about that repository.
Are these XML classes human-generated, or are they generated in some other way?
XML definitions are usually done in XSD.
For example http://intel.com/wbem/wscim/1/amt-schema/1/AMT_EthernetPortSettings is there an xsd definition of a class like this?

Actually my purpose is to generate the amt class in java.

**Comment by bwendlandt-intel** [comment]
Hello!

Development of wsman-messages (and majority of go-wsman-messages) were manual efforts through the use of the Intel AMT SDK documentation.  The SDK does provide MOF files but we were not able to use them for generation although potentially possible. [You can see some info about them and the classes in general in the SDK Docs](https://software.intel.com/sites/manageability/AMT_Implementation_and_Reference_Guide/default.htm?turl=WordDocuments%2Fwsmanagementclassreference.htm).

[You can download the SDK from here.](https://www.intel.com/content/www/us/en/download/704388/intel-active-management-technology-intel-amt-software-development-kit-sdk.html?cache=1639697797).  The MOFs should be in the `WS-Management**Module.zip` directories.  I believe Java has a spec, JMI, that might make use of the MOFs. But, I am not overly familiar with that path.

I'll close the issue, but feel free to re-open if you have follow-on questions.
